### ISSUE TITLE
Options' object has no attribute 'filter_nsfw

### ISSUE THREAD

**Issue by SvetZitrka** [Kahsolt/stable-diffusion-webui-sonar#2]
Nejde mi generovat obrázky a hlásí mi to chybu: AttributeError: 'Options' object has no attribute 'filter_nsfw'

After installation, we left everything default. I tried several models, the result is the same.

`100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  6.58it/s]
Error completing request5:16,  7.86it/s]
Arguments: ('eggs', '', 'None', 'None', 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 5, False, 'LoRA', 'None', 1, 'LoRA', 'None', 1, 'LoRA', 'None', 1, 'LoRA', 'None', 1, 'LoRA', 'None', 1, 'Refresh models', '', '', False, False, False, False, '', 1, '', 0, '', True, False, False, '{inspiration}', None, 'Euler a', 0.95, 0.75, 'zero', 'pos', 0, -0.002, 5, 0, -0.02, False, 'linear', 0.01, 0.0, 0.75, None) {}
Traceback (most recent call last):
  File "d:\AI\stable-diffusion-webui\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "d:\AI\stable-diffusion-webui\modules\call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "D:\AI\stable-diffusion-webui\modules\txt2img.py", line 49, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "D:\AI\stable-diffusion-webui\modules\scripts.py", line 337, in run
    processed = script.run(p, *script_args)
  File "D:\AI\stable-diffusion-webui\extensions\stable-diffusion-webui-sonar\scripts\sonar.py", line 963, in run
    proc = process_images(p)
  File "D:\AI\stable-diffusion-webui\extensions\stable-diffusion-webui-sonar\scripts\sonar.py", line 80, in process_images
    res = process_images_inner(p)
  File "D:\AI\stable-diffusion-webui\extensions\stable-diffusion-webui-sonar\scripts\sonar.py", line 199, in process_images_inner
    if opts.filter_nsfw:
  File "d:\AI\stable-diffusion-webui\modules\shared.py", line 496, in __getattr__
    return super(Options, self).__getattribute__(item)
AttributeError: 'Options' object has no attribute 'filter_nsfw'`

**Comment by Kahsolt** [comment]
Thanks for informing. 
I've noticed that recent sd-webui changed kernel code layout a lot, many things need an update, I will fix this tomorrow :)
