### ISSUE TITLE
Getting ImportError when Sonar is loading in

### ISSUE THREAD

**Issue by dernox47** [Kahsolt/stable-diffusion-webui-sonar#26]
When I run the WebUI i get this import error:

```
*** Error loading script: sonar.py
    Traceback (most recent call last):
      File "D:\SDlatest\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\SDlatest\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\SDlatest\extensions\stable-diffusion-webui-sonar\scripts\sonar.py", line 18, in <module>
        from modules.script_callbacks import ExtraNoiseParams, extra_noise_callback
    ImportError: cannot import name 'ExtraNoiseParams' from 'modules.script_callbacks' (D:\SDlatest\modules\script_callbacks.py)
```

What should I do about it? It does not load and appear in the script dropdown menu.

**Comment by Kahsolt** [comment]
tell me your sd-webui version or commit hash, it seems too old

**Comment by dernox47** [comment]
Commit hash says: \<none\> Version: 1.5.2

**Comment by dernox47** [comment]
closed
