### ISSUE TITLE
"Error loading script: sonar.py" after updating A1111's webui to latest commit

### ISSUE THREAD

**Issue by illtellyoulater** [Kahsolt/stable-diffusion-webui-sonar#4]
getting this on windows 10 after updating webui to aa4688eb8345de583070ca9ddb4c6f585f06762b

```
Error loading script: sonar.py
Traceback (most recent call last):
  File "C:\Users\username\Downloads\generative-nn-models\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\username\Downloads\generative-nn-models\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\username\Downloads\generative-nn-models\stable-diffusion-webui\extensions\stable-diffusion-webui-sonar\scripts\sonar.py", line 445, in <module>
    def sample_naive(model:CFGDenoiser, x:Tensor, sigmas:List, extra_args={}, callback=None, *args):
NameError: name 'CFGDenoiser' is not defined
```

**Comment by illtellyoulater** [comment]
More info: this is due to WebUI updated to reorganize sampler code recently.
It goes away by doing: git checkout cbd6329488beafe036ea3a3d0cea1a6940105cf9 (the last commit before sampler reorg).

How this was fixed in another extension: https://github.com/mcmonkeyprojects/sd-dynamic-thresholding/issues/2

**Comment by RainehDaze** [comment]
Looks like KDifffusionSampler and CFGDenoiser are now in sd_samplers_kdiffusion, while setup_img2imgsteps is in sd_samplers_common.

I'd change the import lines myself, but I can't work out where inspect is being imported _from_

It's only this line that needs changing:

`from modules.sd_samplers import *
KDiffusionSampler, CFGDenoiser, SamplerData, setup_img2img_steps, inspect 
`
