### ISSUE TITLE
unable to use naive due to "RuntimeError: Input type (float) and bias type (struct c10::Half) should be the same"

### ISSUE THREAD

**Issue by kazi-nasir** [Kahsolt/stable-diffusion-webui-sonar#5]
full error here:
```
Traceback (most recent call last):
  File "E:\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "E:\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "E:\stable-diffusion-webui\modules\txt2img.py", line 53, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "E:\stable-diffusion-webui\modules\scripts.py", line 376, in run
    processed = script.run(p, *script_args)
  File "E:\stable-diffusion-webui\extensions\stable-diffusion-webui-sonar\scripts\sonar.py", line 924, in run
    proc = process_images(p)
  File "E:\stable-diffusion-webui\extensions\stable-diffusion-webui-sonar\scripts\sonar.py", line 82, in process_images
    res = process_images_inner(p)
  File "E:\stable-diffusion-webui\extensions\stable-diffusion-webui-sonar\scripts\sonar.py", line 227, in process_images_inner
    samples_ddim = sample_func(p, conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "E:\stable-diffusion-webui\extensions\stable-diffusion-webui-sonar\scripts\sonar.py", line 328, in StableDiffusionProcessingTxt2Img_sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "E:\stable-diffusion-webui\extensions\stable-diffusion-webui-sonar\scripts\sonar.py", line 781, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "E:\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 190, in launch_sampling
    return func()
  File "E:\stable-diffusion-webui\extensions\stable-diffusion-webui-sonar\scripts\sonar.py", line 781, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "E:\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "E:\stable-diffusion-webui\extensions\stable-diffusion-webui-sonar\scripts\sonar.py", line 509, in sample_naive_ex
    latent_ref = sd_model.get_first_stage_encoding(sd_model.encode_first_stage(x_ref))     # [B, C=4, H=64, W=64]
  File "E:\stable-diffusion-webui\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "E:\stable-diffusion-webui\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "E:\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "E:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 830, in encode_first_stage
    return self.first_stage_model.encode(x)
  File "E:\stable-diffusion-webui\modules\lowvram.py", line 48, in first_stage_model_encode_wrap
    return first_stage_model_encode(x)
  File "E:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\autoencoder.py", line 83, in encode
    h = self.encoder(x)
  File "E:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\model.py", line 523, in forward
    hs = [self.conv_in(x)]
  File "E:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\stable-diffusion-webui\extensions-builtin\Lora\lora.py", line 182, in lora_Conv2d_forward
    return lora_forward(self, input, torch.nn.Conv2d_forward_before_lora(self, input))
  File "E:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "E:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (float) and bias type (struct c10::Half) should be the same
```

**Comment by Kahsolt** [comment]
It seems an error causing by LoRA, I'm not familiar with that... 
Maybe you can refer to this: https://github.com/cloneofsimo/lora/issues/10 (?
