### ISSUE TITLE
Unable to use naive

### ISSUE THREAD

**Issue by AndreyRGW** [Kahsolt/stable-diffusion-webui-sonar#7]
```
Traceback (most recent call last):
  File "F:\WBC\sdwb\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "F:\WBC\sdwb\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "F:\WBC\sdwb\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "F:\WBC\sdwb\modules\processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "F:\WBC\sdwb\modules\processing.py", line 632, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "F:\WBC\sdwb\extensions\stable-diffusion-webui-sonar\scripts\sonar.py", line 686, in <lambda>
    p.sample = lambda *args, **kwargs: StableDiffusionProcessingTxt2Img_sample(p, *args, **kwargs)
  File "F:\WBC\sdwb\extensions\stable-diffusion-webui-sonar\scripts\sonar.py", line 78, in StableDiffusionProcessingTxt2Img_sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "F:\WBC\sdwb\extensions\stable-diffusion-webui-sonar\scripts\sonar.py", line 530, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "F:\WBC\sdwb\modules\sd_samplers_kdiffusion.py", line 225, in launch_sampling
    return func()
  File "F:\WBC\sdwb\extensions\stable-diffusion-webui-sonar\scripts\sonar.py", line 530, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "F:\WBC\sdwb\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "F:\WBC\sdwb\extensions\stable-diffusion-webui-sonar\scripts\sonar.py", line 258, in sample_naive_ex
    latent_ref = sd_model.get_first_stage_encoding(sd_model.encode_first_stage(x_ref))     # [B, C=4, H=64, W=64]
  File "F:\WBC\sdwb\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "F:\WBC\sdwb\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "F:\WBC\sdwb\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "F:\WBC\sdwb\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 830, in encode_first_stage
    return self.first_stage_model.encode(x)
  File "F:\WBC\sdwb\modules\lowvram.py", line 48, in first_stage_model_encode_wrap
    return first_stage_model_encode(x)
  File "F:\WBC\sdwb\repositories\stable-diffusion-stability-ai\ldm\models\autoencoder.py", line 83, in encode
    h = self.encoder(x)
  File "F:\WBC\sdwb\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\WBC\sdwb\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\model.py", line 523, in forward
    hs = [self.conv_in(x)]
  File "F:\WBC\sdwb\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\WBC\sdwb\venv\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "F:\WBC\sdwb\venv\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (float) and bias type (struct c10::Half) should be the same
```

**Comment by Kahsolt** [comment]
This is a known issue but seems not sonar's fault, because sonar does not take over control the VAE encoding/decoding process.
However, this dtype mismatch error could be avoid by adding option `COMMANDLINE_ARGS=--no-half-vae` to the launcher script `webui-user.bat`.

**Comment by AndreyRGW** [comment]
> This is a known issue but seems not sonar's fault, because sonar does not take over control the VAE encoding/decoding process. However, this dtype mismatch error could be avoid by adding option `COMMANDLINE_ARGS=--no-half-vae` to the launcher script `webui-user.bat`.

I disabled "--no-half-vae", but the error remains the same.
