### ISSUE TITLE
ModuleNotFoundError: No module named 'modules.sd_samplers_common'

### ISSUE THREAD

**Issue by hktalent** [Kahsolt/stable-diffusion-webui-sonar#9]
```
Error loading script: sonar.py
Traceback (most recent call last):
  File "/content/drive/My Drive/ai/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/drive/My Drive/ai/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/content/drive/My Drive/ai/stable-diffusion-webui/extensions/stable-diffusion-webui-sonar/scripts/sonar.py", line 19, in <module>
    from modules.sd_samplers_common import setup_img2img_steps, SamplerData
ModuleNotFoundError: No module named 'modules.sd_samplers_common'

```

**Comment by Kahsolt** [comment]
It seems you are running from a webui repo very out-of-date, since `modules.sd_samplers_common` has been introduced into webui core for weeks. Just try updating your webui :)

**Comment by hktalent** [comment]
```
no config file: /content/drive/My Drive/ai/stable-diffusion-webui/extensions/Stable-Diffusion-Webui-Prompt-Translator/prompt_translator.cfg
Scan MarianMT model
No MarianMT folder, no need scan
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
Error loading script: sonar.py
Traceback (most recent call last):
  File "/content/drive/My Drive/ai/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/drive/My Drive/ai/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/content/drive/My Drive/ai/stable-diffusion-webui/extensions/stable-diffusion-webui-sonar/scripts/sonar.py", line 19, in <module>
    from modules.sd_samplers_common import setup_img2img_steps, SamplerData
ModuleNotFoundError: No module named 'modules.sd_samplers_common'

[text2prompt] Following databases are available:
    all-mpnet-base-v2 : danbooru_strict
Loading weights [7234b76e42] from /content/drive/My Drive/ai/stable-diffusion-webui/models/Stable-diffusion/chilloutmixni.safetensors
Creating model from config: /content/drive/My Drive/ai/stable-diffusion-webui/configs/v1-inference.yaml
```

**Comment by Kahsolt** [comment]
Can you find out your webui's current commit hash? Or show me your scripts under `modules` containing name `sd_samplers`?
That original `modules.sd_samplers` file should have been been splited into several scripts:

![image](https://user-images.githubusercontent.com/22111194/229155483-ee6758a1-8802-428b-8198-74ffd285a0b9.png)

though compatible fixes are possible in theory and might work in practice, it will mess up the code.
Hesitate to make this fix unless really necessary ;(

**Comment by hktalent** [comment]
https://colab.research.google.com/drive/1Fj9LdDVB2SZyDH2y8nPRNkxu1j9J4a1z?authuser=1#scrollTo=sBbcB4vwj_jm
